---
- hosts: localhost
  become: true
  vars_files:
    - vars/config.yml
  vars:
    appdata_directory: "/home/{{ user_name }}/appdata"
    link_path: "{{mount_point}}/appdata"
  tasks:
    - name: Install necessary packages
      apt:
        name:
          - samba
          - samba-common
          - parted
        state: present

    - name: Check if the partition exists
      command: lsblk -no FSTYPE "{{ drive_device }}"
      register: partition_check
      ignore_errors: true
      changed_when: false

    - name: Fail if the partition does not exist
      fail:
        msg: "The partition {{ drive_device }} does not exist."
      when: partition_check.rc != 0

    - name: Check if drive is already mounted
      shell: mount | grep "{{ mount_point }}"
      register: is_mounted
      changed_when: false
      ignore_errors: true

    - name: Setup drive
      when: is_mounted.rc != 0
      block:
        - name: Format the drive
          filesystem:
            fstype: ext4
            dev: "{{ drive_device }}"
          when: format_drive | default(false)

        - name: Create a mount point
          file:
            path: "{{ mount_point }}"
            state: directory

        - name: Mount the drive
          mount:
            path: "{{ mount_point }}"
            src: "{{ drive_device }}"
            fstype: ext4
            state: mounted
            opts: defaults

    - name: Set ownership of the mount point
      file:
        path: "{{ mount_point }}"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "0775"
        recurse: yes

    - name: Configure Samba share
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [{{ samba_share_name }}]
          path = {{ mount_point }}
          browseable = yes
          writeable = yes
          guest ok = yes
          follow symlinks = yes # turning on simlinks and wide links is generally unsafe, but should be fine since we're on a local network.
          wide links = yes
          write list = {{ user_name }}
          create mask = 0777
          directory mask = 0777
      notify:
        - restart samba

    - name: Check if appdata directory exists
      stat:
        path: "{{ appdata_directory }}"
      register: appdata_stat

    - name: Create appdata link
      when: not appdata_stat.stat.exists
      block:
        - name: Create appdata directory in user's home
          file:
            path: "{{ appdata_directory }}"
            state: directory
            owner: "{{ user_name }}"
            group: "{{ user_name }}"
            mode: "0755"

        - name: Create symbolic link to appdata directory in the share
          file:
            src: "{{ appdata_directory }}"
            dest: "{{ link_path }}"
            state: link
            force: yes

  handlers:
    - name: restart samba
      service:
        name: smbd
        state: restarted
