---
- name: Update all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist

- name: Install required system packages
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
