---
- name: Add the NVIDIA GPG key
  ansible.builtin.apt_key:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    keyring: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

# Have to use a shell command instead of `ansible.builtin.apt_repository` since we can't seem to fetch the correct release version.
- name: Add NVIDIA Container Toolkit repository
  ansible.builtin.shell: |
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install NVIDIA Container Toolkit
  ansible.builtin.apt:
    name: nvidia-container-toolkit
    state: present

- name: Configure Docker to use NVIDIA runtime
  ansible.builtin.shell:
    cmd: nvidia-ctk runtime configure --runtime=docker

- name: Restart Docker daemon
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: yes
