user_name: rmacwha # Replace with your desired user name
drive_device: /dev/sdb # Replace with your drive device
mount_point: /mnt/media # Replace with your desired mount point
samba_share_name: Home # Replace with your desired share name
