---
version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    ports:
      - 8096:8096
    volumes:
      - /appdata/jellyfin:/config
      - /mnt/home/media:/media
      - /mnt/home/downloads/torrents:/torrents
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    restart: unless-stopped
